// Mocks generated by Mockito 5.4.6 from annotations
// in atomberg_fan_controller/test/unit/usecases/control_device_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:atomberg_fan_controller/core/utils/result.dart' as _i2;
import 'package:atomberg_fan_controller/domain/entities/device_entity.dart'
    as _i5;
import 'package:atomberg_fan_controller/domain/repositories/device_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceRepository extends _i1.Mock implements _i3.DeviceRepository {
  MockDeviceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.DeviceEntity>>> fetchDevices() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDevices,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.DeviceEntity>>>.value(
            _FakeResult_0<List<_i5.DeviceEntity>>(
          this,
          Invocation.method(
            #fetchDevices,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.DeviceEntity>>>);

  @override
  _i4.Future<_i2.Result<_i5.DeviceEntity>> fetchDevice(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDevice,
          [deviceId],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.DeviceEntity>>.value(
            _FakeResult_0<_i5.DeviceEntity>(
          this,
          Invocation.method(
            #fetchDevice,
            [deviceId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.DeviceEntity>>);

  @override
  _i4.Future<_i2.Result<bool>> controlPower(
    String? deviceId,
    bool? powerOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlPower,
          [
            deviceId,
            powerOn,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #controlPower,
            [
              deviceId,
              powerOn,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<bool>> controlSpeed(
    String? deviceId,
    int? speed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlSpeed,
          [
            deviceId,
            speed,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #controlSpeed,
            [
              deviceId,
              speed,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<bool>> controlLight(
    String? deviceId,
    bool? lightOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlLight,
          [
            deviceId,
            lightOn,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #controlLight,
            [
              deviceId,
              lightOn,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);

  @override
  _i4.Future<_i2.Result<bool>> controlBreeze(
    String? deviceId,
    bool? breezeOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlBreeze,
          [
            deviceId,
            breezeOn,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<bool>>.value(_FakeResult_0<bool>(
          this,
          Invocation.method(
            #controlBreeze,
            [
              deviceId,
              breezeOn,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<bool>>);
}
