// Mocks generated by Mockito 5.4.6 from annotations
// in atomberg_fan_controller/test/unit/repositories/device_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:atomberg_fan_controller/data/models/control_response_model.dart'
    as _i4;
import 'package:atomberg_fan_controller/data/models/device_model.dart' as _i3;
import 'package:atomberg_fan_controller/data/services/api_service.dart' as _i5;
import 'package:atomberg_fan_controller/data/services/storage_service.dart'
    as _i7;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeviceModel_1 extends _i1.SmartFake implements _i3.DeviceModel {
  _FakeDeviceModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeControlResponseModel_2 extends _i1.SmartFake
    implements _i4.ControlResponseModel {
  _FakeControlResponseModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.Future<List<_i3.DeviceModel>> fetchDevices() => (super.noSuchMethod(
        Invocation.method(
          #fetchDevices,
          [],
        ),
        returnValue:
            _i6.Future<List<_i3.DeviceModel>>.value(<_i3.DeviceModel>[]),
      ) as _i6.Future<List<_i3.DeviceModel>>);

  @override
  _i6.Future<_i3.DeviceModel> fetchDevice(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDevice,
          [deviceId],
        ),
        returnValue: _i6.Future<_i3.DeviceModel>.value(_FakeDeviceModel_1(
          this,
          Invocation.method(
            #fetchDevice,
            [deviceId],
          ),
        )),
      ) as _i6.Future<_i3.DeviceModel>);

  @override
  _i6.Future<_i4.ControlResponseModel> controlPower(
    String? deviceId,
    bool? powerOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlPower,
          [
            deviceId,
            powerOn,
          ],
        ),
        returnValue: _i6.Future<_i4.ControlResponseModel>.value(
            _FakeControlResponseModel_2(
          this,
          Invocation.method(
            #controlPower,
            [
              deviceId,
              powerOn,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ControlResponseModel>);

  @override
  _i6.Future<_i4.ControlResponseModel> controlSpeed(
    String? deviceId,
    int? speed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlSpeed,
          [
            deviceId,
            speed,
          ],
        ),
        returnValue: _i6.Future<_i4.ControlResponseModel>.value(
            _FakeControlResponseModel_2(
          this,
          Invocation.method(
            #controlSpeed,
            [
              deviceId,
              speed,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ControlResponseModel>);

  @override
  _i6.Future<_i4.ControlResponseModel> controlLight(
    String? deviceId,
    bool? lightOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlLight,
          [
            deviceId,
            lightOn,
          ],
        ),
        returnValue: _i6.Future<_i4.ControlResponseModel>.value(
            _FakeControlResponseModel_2(
          this,
          Invocation.method(
            #controlLight,
            [
              deviceId,
              lightOn,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ControlResponseModel>);

  @override
  _i6.Future<_i4.ControlResponseModel> controlBreeze(
    String? deviceId,
    bool? breezeOn,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #controlBreeze,
          [
            deviceId,
            breezeOn,
          ],
        ),
        returnValue: _i6.Future<_i4.ControlResponseModel>.value(
            _FakeControlResponseModel_2(
          this,
          Invocation.method(
            #controlBreeze,
            [
              deviceId,
              breezeOn,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ControlResponseModel>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i7.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String?> getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool?> getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  _i6.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int?> getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: _i6.Future<int?>.value(),
      ) as _i6.Future<int?>);

  @override
  _i6.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}
