// Mocks generated by Mockito 5.4.6 from annotations
// in atomberg_fan_controller/test/widget/device_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:atomberg_fan_controller/core/utils/result.dart' as _i3;
import 'package:atomberg_fan_controller/domain/entities/device_entity.dart'
    as _i6;
import 'package:atomberg_fan_controller/domain/repositories/device_repository.dart'
    as _i2;
import 'package:atomberg_fan_controller/domain/usecases/control_device_usecase.dart'
    as _i8;
import 'package:atomberg_fan_controller/domain/usecases/fetch_device_usecase.dart'
    as _i7;
import 'package:atomberg_fan_controller/domain/usecases/fetch_devices_usecase.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceRepository_0 extends _i1.SmartFake
    implements _i2.DeviceRepository {
  _FakeDeviceRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchDevicesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchDevicesUseCase extends _i1.Mock
    implements _i4.FetchDevicesUseCase {
  MockFetchDevicesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeviceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeviceRepository);

  @override
  _i5.Future<_i3.Result<List<_i6.DeviceEntity>>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<List<_i6.DeviceEntity>>>.value(
            _FakeResult_1<List<_i6.DeviceEntity>>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<List<_i6.DeviceEntity>>>);
}

/// A class which mocks [FetchDeviceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchDeviceUseCase extends _i1.Mock
    implements _i7.FetchDeviceUseCase {
  MockFetchDeviceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeviceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeviceRepository);

  @override
  _i5.Future<_i3.Result<_i6.DeviceEntity>> execute(String? deviceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [deviceId],
        ),
        returnValue: _i5.Future<_i3.Result<_i6.DeviceEntity>>.value(
            _FakeResult_1<_i6.DeviceEntity>(
          this,
          Invocation.method(
            #execute,
            [deviceId],
          ),
        )),
      ) as _i5.Future<_i3.Result<_i6.DeviceEntity>>);
}

/// A class which mocks [ControlDeviceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockControlDeviceUseCase extends _i1.Mock
    implements _i8.ControlDeviceUseCase {
  MockControlDeviceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeDeviceRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.DeviceRepository);

  @override
  _i5.Future<_i3.Result<bool>> execute({
    required String? deviceId,
    required _i8.ControlAction? action,
    dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #deviceId: deviceId,
            #action: action,
            #value: value,
          },
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #deviceId: deviceId,
              #action: action,
              #value: value,
            },
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);
}
